<!-- The login form which is displayed on the index of the website  -->
<!DOCTYPE>
<html>
<head>
    <meta name ="viewport" content ="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./css/CSSmax.css">

    <section class ="indexlogin">

        <div class = "signup">
            <div class = "cont-header">
                <H3>Login</H3>
                <p>Administrator Login</p>
                <form class="signupform" action=""  method="POST">
                    <div class="form-control">
                        <input type="text" name="username" placeholder="Username">
                        <input type="password" name="password" placeholder="Password">

                    </div>
                    <button type="submit" name="loginbutton" class="btn btn-outline-krm">Login</button>
                </form>
            </div>
        </div>
    </section>
