
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Dashboard · KRM</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./css/dashboard.css" rel="stylesheet">
</head>
<body>

<!-- Header  -->
<?php include('./Views/template/krmHeader.phtml') ?>

<!--  Nav Bar   -->
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="./home.php">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href= " ./candidates.php">
                            <span data-feather="file"></span>
                            Candidate list
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href= " ./addCandidate.php">
                            <span data-feather="file"></span>
                            Add Candidate
                        </a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link" href="./offer.php">
                            <span data-feather="circle"></span>
                            Job offers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./training.php">
                            <span data-feather="users"></span>
                            Training
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./list.php">
                            <span data-feather="bar-chart-2"></span>
                            To Do List
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Settings</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="./admin.php">
                            <span data-feather="file-text"></span>
                            Admin
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
<!-- Main body  -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="row">
            <div class="card row align-items-center gx-0">
                <div class="card-body">
                    <h6> Currently On boarding </h6>
                    <span class="h2 mb-0">12</span>
                    <span class="user-40" data-feather="user"></span>
                </div>
            </div>
            <div class="card row align-items-center gx-0">
                <div class="card-body">
                    <h6> Total Candidates </h6>
                    <span class="h2 mb-0">20</span>
                    <span class="user-40" data-feather="user"></span>
                </div>
            </div>
        </div>

        <!-- Chart  -->
        <div class="my-4 w-50">
            <canvas id="myChart" width="450" height="250"></canvas>
        </div>
        </div>

        <!-- Candidate List  -->
            <div class="table-responsive scrollbar">
                <table class="table table-dashboard mb-0 table-borderless fs--1 border-200">
                    <thead class="table-header">
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone number</th>
                    </tr>
                    </thead>
                    <tbody>
                <?php foreach($view->dashboardDataSet as $dashboardData){
                    echo '<tr class="tableRow"><td class="tableData">' . $dashboardData->getCandidatefirstName() . '</td><td class="tableData">' . $dashboardData->getCandidatelastName() . '</td><td class="tableData">' . $dashboardData->getCandidateEmail() . '</td><td class="tableData">' . $dashboardData->getCandidatePhoneNumber() . '</td></tr>';
                } ?>
                    </tbody>
                </table>
            </div>
        </main>
    </div>
</div>

<script src="./js/bootstrap.bundle.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="./js/dashboard.js"></script>
</body>
</html>
