<?php
?>
<?php
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Dashboard · KRM</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">



    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="./css/dashboard.css" rel="stylesheet">
</head>
<body>

<!-- Includes the header -->
<?php include('./Views/template/krmHeader.phtml') ?>

<!-- NavBar  -->
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="./home.php">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href= " ./candidates.php">
                            <span data-feather="file"></span>
                            Candidate list
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href= " ./addCandidate.php">
                            <span data-feather="file"></span>
                            Add Candidate
                        </a>
                    </li>  
                    <li class="nav-item">
                        <a class="nav-link active" href="./offer.php">
                            <span data-feather="circle"></span>
                            Job offers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="./training.php">
                            <span data-feather="users"></span>
                            Training
                        </a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="./list.php">
                            <span data-feather="bar-chart-2"></span>
                            To Do List
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Settings</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="./admin.php">
                            <span data-feather="file-text"></span>
                            Admin
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">



<!-- Display the job offers  -->
            <h2>Job offers</h2>
            <table class="table table-dashboard mb-0 table-borderless fs--1 border-200">
  <thead class="table-header">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Job Title</th>
      <th scope="col">Number of candidates</th>
      <th scope="col"> Last Updated</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Software engineer</td>
      <td>5</td>
      <td>12th January 2021</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Programmer</td>
      <td>2</td>
      <td>10th January 2021</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>HR</td>
      <td>3</td>
      <td>15th January 2021</td>
    </tr>
  </tbody>
</table>

        </main>
    </div>
</div>

<script src="./js/bootstrap.bundle.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="./js/dashboard.js"></script>
</body>
</html>

